conditioning:
  method: BOMO
  params:
    scale: 13
    miu: 0.01
    sparsity: 6
    num_proj: 30
    circle: False
    

data:
  name: fundus
  root: ./data/fundus1/

measurement:
  operator:
    name: noise
  
  noise: 
    name: clean
